#!/usr/bin/env bash
# Turns tester-emails.txt (NOT committed - personal data) into tester-hashes.txt (committed).
# The Android build only ships SHA-256 hashes of the tester emails, never the emails.
set -euo pipefail
cd "$(dirname "$0")"
{
  echo "# SHA-256 (hex) of lower-cased tester emails. Generated by hash-testers.sh from"
  echo "# tester-emails.txt, which stays local. Empty this file before the production build."
  grep -v '^\s*#' tester-emails.txt | sed 's/#.*//' | tr -d ' \t\r' | tr 'A-Z' 'a-z' | grep '@' | sort -u \
    | while read -r e; do printf '%s' "$e" | sha256sum | cut -d' ' -f1; done
} > tester-hashes.txt
echo "tester-hashes.txt: $(grep -vc '^#' tester-hashes.txt) hashes"
